#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

########
# Xorg #
########
xsetroot -cursor_name left_ptr &
numlockx &

# Screen blanking and autosuspend
xset s 0 0 &
xset dpms 0 0 0 &
xidlehook --socket /tmp/xidlehook_socket.sock \
    --not-when-fullscreen --not-when-audio \
    --timer 540 'notify-send "Screen locking in 1 minute"' ''\
    --timer 60 'xset dpms force off' '' \
    --timer 300 'systemctl suspend' '' &


# setxkbmap -layout us &
# setxkbmap -option compose:rctrl &

# Monitors
xrandr --output VGA-1 --auto --right-of HDMI-1
xrandr --output DVI-D-1 --auto --left-of HDMI-1

#################
# Customization #
#################
feh --bg-fill $HOME/Pictures/Wallpapers/wall2.jpg &
picom --config $HOME/.config/picom/picom.conf &
$HOME/.config/polybar/launch.sh &
wmname LG3D &

################
# Applications #
################
dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
greenclip daemon &
# /usr/bin/dropbox &
telegram-desktop -startintray &

#################
# Bspwm configs #
#################
bspc monitor DVI-D-1 -d 1 4
bspc monitor HDMI-1 -d 2 5
bspc monitor VGA-1 -d 3 6

bspc config border_width         1
bspc config window_gap           3

bspc config active_border_color     \#30302f
bspc config normal_border_color     \#30302f
bspc config focused_border_color    \#817f7f

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus      any
bspc config ignore_ewmh_focus true

# Rules
bspc rule -a Gnome-calculator state=floating follow=on
bspc rule -a ObinsKit state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a QEMU state=floating follow=on
bspc rule -a "Jetbrains Toolbox" state=floating follow=on

