#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

########
# Xorg #
########
xsetroot -cursor_name left_ptr &
numlockx &

# Screen blanking and autosuspend
xset s 0 0 &
xset dpms 0 0 0 &

xidlehook --socket /tmp/xidlehook_socket.sock \
    --not-when-fullscreen --not-when-audio \
    --timer 540 'notify-send "Suspending in 1 minute"' ''\
    --timer 60 'betterlockscreen --lock dim' '' &
#     --timer 60 'systemctl suspend' '' &


# setxkbmap -layout us &
# setxkbmap -option compose:rctrl &

# Monitors
xrandr --output VGA-1 --auto --right-of HDMI-1
xrandr --output DVI-D-1 --auto --left-of HDMI-1

#################
# Customization #
#################
feh --bg-fill $HOME/Pictures/Wallpapers/wall13.jpg &
picom --config $HOME/.config/picom/picom.conf &
$HOME/.config/polybar/launch.sh &
wmname LG3D &

################
# Applications #
################
dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
greenclip daemon &
/usr/bin/dropbox &
telegram-desktop -startintray &

#################
# Bspwm configs #
#################

# N_MONITORS=$(xrandr --listmonitors | grep Monitors | awk '{ print $2 }')
# if [ N_MONITORS -eq '1' ]; then
#     bspc monitor HDMI-1 -d 1 2 3 4 5
# else

bspc monitor DVI-D-0 -d 1 2
bspc monitor HDMI-A-0 -d 3 4
bspc monitor VGA-0 -d 5 6

# fi

bspc config border_width         2
bspc config window_gap           10

bspc config active_border_color     \#30302f
bspc config normal_border_color     \#30302f
bspc config focused_border_color    \#817f7f

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus      any
bspc config ignore_ewmh_focus true

# Rules -- use `xtitle $(bspc query -N -n .window)` to get window names
bspc rule -a Gnome-calculator state=floating follow=on
bspc rule -a ObinsKit state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a QEMU state=floating follow=on
bspc rule -a "Jetbrains Toolbox" state=floating follow=on
bspc rule -a win0 state=floating follow=on
bspc rule -a SimpleScreenRecorder state=floating follow=on
# bspc rule -a "Org.gnome.Nautilus" state=floating follow=on

