#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

# Xorg set
xsetroot -cursor_name left_ptr &
xset led 3 &
setxkbmap -layout it &
numlockx &

# Monitors
xrandr --output VGA-1 --auto --right-of HDMI-1
xrandr --output DVI-D-1 --auto --left-of HDMI-1

# Customization
feh --bg-fill ~/Pictures/Wallpapers/wall.jpg &
picom --config ~/.config/picom/picom.conf & # standard config
~/.config/polybar/launch.sh & # number 12 @ adi1090x/polybar-themes
wmname LG3D &

# Applications
dunst &
telegram-desktop -startintray &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
greenclip daemon &

# Bspwm configs
bspc monitor DVI-D-1 -d 1 4 5
bspc monitor HDMI-1 -d 2 6 7
bspc monitor VGA-1 -d 3 8 9

bspc config border_width         2
bspc config window_gap           9

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a Chromium:crx_diankknpkndanachmlckaikddgcehkod state=floating follow=on # chrome extension
bspc rule -a Gnome-calculator state=floating follow=on
